source ~/dev/gadamer/autoload/gadamer/annotations.vim
source ~/dev/gadamer/autoload/gadamer/signs.vim
source ~/dev/gadamer/autoload/gadamer/mode.vim
source ~/dev/gadamer/autoload/gadamer/config.vim
source ~/dev/gadamer/autoload/gadamer/edit.vim
source ~/dev/gadamer/autoload/gadamer/list.vim
source ~/dev/gadamer/autoload/gadamer/view.vim
source ~/dev/gadamer/autoload/gadamer.vim
source ~/dev/gadamer/plugin/gadamer.vim
